import {ItemType} from "./item";

export const enemy_stats = {
  "prison_guard"  : { "H": 3, "C": 3, "D": 1 },
  "prison_soldier": { "H": 3, "C": 2, "D": 1 },
  "prison_warden" : { "H": 5, "C": 4, "D": 2 },
};

export const item_stats = {
  "fist"                  : { "T": ItemType.WEAPON, "R": false, "D": 1, "S": 1 },
  "baton"                 : { "T": ItemType.WEAPON, "R": false, "D": 1, "S": 1 },
  "mace"                  : { "T": ItemType.WEAPON, "R": false, "D": 2, "S": 1 },
  "battle_axe"            : { "T": ItemType.WEAPON, "R": false, "D": 3, "S": 1 },
  "em_rod"                : { "T": ItemType.WEAPON, "R": false, "D": 4, "S": 1 },
  "double_em_rod"         : { "T": ItemType.WEAPON, "R": false, "D": 5, "S": 1 },
  "faraday_pole"          : { "T": ItemType.WEAPON, "R": false, "D": 6, "S": 1 },
  "quark_rod"             : { "T": ItemType.WEAPON, "R": false, "D": 7, "S": 1 },
  "quark_staff"           : { "T": ItemType.WEAPON, "R": false, "D": 8, "S": 1 },
  "quark_halberd"         : { "T": ItemType.WEAPON, "R": false, "D": 9, "S": 1 },
  "knife"                 : { "T": ItemType.WEAPON, "R": false, "D": 1, "S": 1 },
  "spear"                 : { "T": ItemType.WEAPON, "R": false, "D": 2, "S": 1 },
  "katana"                : { "T": ItemType.WEAPON, "R": false, "D": 3, "S": 1 },
  "stunner"               : { "T": ItemType.WEAPON, "R": false, "D": 4, "S": 1 },
  "electroblade"          : { "T": ItemType.WEAPON, "R": false, "D": 5, "S": 1 },
  "laser_blade"           : { "T": ItemType.WEAPON, "R": false, "D": 6, "S": 1 },
  "quark_spike"           : { "T": ItemType.WEAPON, "R": false, "D": 7, "S": 1 },
  "quark_blade"           : { "T": ItemType.WEAPON, "R": false, "D": 8, "S": 1 },
  "quark_spear"           : { "T": ItemType.WEAPON, "R": false, "D": 9, "S": 1 },
  "pistol"                : { "T": ItemType.WEAPON, "R": true,  "D": 1, "S": 1 },
  "shotgun"               : { "T": ItemType.WEAPON, "R": true,  "D": 2, "S": 1 },
  "assault_rifle"         : { "T": ItemType.WEAPON, "R": true,  "D": 3, "S": 1 },
  "railgun"               : { "T": ItemType.WEAPON, "R": true,  "D": 4, "S": 1 },
  "electrified_railgun"   : { "T": ItemType.WEAPON, "R": true,  "D": 5, "S": 1 },
  "laser_gun"             : { "T": ItemType.WEAPON, "R": true,  "D": 6, "S": 1 },
  "x_ray_gun"             : { "T": ItemType.WEAPON, "R": true,  "D": 7, "S": 1 },
  "gamma_gun"             : { "T": ItemType.WEAPON, "R": true,  "D": 8, "S": 1 },
  "spooky_gun"            : { "T": ItemType.WEAPON, "R": true,  "D": 9, "S": 1 },
  "none"                  : { "T": ItemType.ARMOR, "A": 0 },
  "rigid_vest"            : { "T": ItemType.ARMOR, "A": 1 },
  "combat_suit"           : { "T": ItemType.ARMOR, "A": 2 },
  "reinforced_combat_suit": { "T": ItemType.ARMOR, "A": 3 },
  "force_field_suit"      : { "T": ItemType.ARMOR, "A": 4 },
  "quark_suit"            : { "T": ItemType.ARMOR, "A": 5 },
};
